name: Deploy code to existing environment

on:
  push:
    branches:
      - main
    # paths:
    #   - 'CosmosCRUD/**'
    #   - 'unit-tests/**'
    #   - 'cypress/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

      - name: Clean libraries
        run: |
          rm -rf node_modules
          npm install --omit=dev

      - name: Create ZIP package
        run: zip -r deploy.zip node_modules CosmosCRUD host.json package.json package-lock.json

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List files in current directory
        run: ls -la

      - name: Deploy ARM resource
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: .github/workflows/crc-api-template.json

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: getviewcount
          package: deploy.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5