name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

      - name: Clean libraries
        run: |
          rm -rf node_modules
          npm install --production

      - name: Create deployment directory
        run: |
          mkdir deployment
          cp -r CosmosCRUD deployment/
          cp -r node_modules deployment/
          cp host.json deployment/
          cp package.json deployment/
          cp package-lock.json deployment/

      - name: Create ZIP package
        run: zip -r deploy.zip ./deployment/*

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: getviewcount
          package: deploy.zip
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5